// Scintilla source code edit control
/** @file SciLexer.h
 ** Interface to the added lexer functions in the SciLexer version of the edit control.
 **/
// Copyright 1998-2002 by Neil Hodgson <neilh@scintilla.org>
// The License.txt file describes the conditions under which this software may be distributed.

// Most of this file is automatically generated from the Scintilla.iface interface definition
// file which contains any comments about the definitions. HFacer.py does the generation.

#ifndef SCILEXER_H
#define SCILEXER_H

// SciLexer features - not in standard Scintilla

// modified by Mitchell
//++Autogenerated -- start of section automatically generated from Scintilla.iface
#define SCLEX_CONTAINER 0
#define SCLEX_NULL 1
#define SCLEX_LPEG 2
#define SCLEX_AUTOMATIC 1000
#define SCE_LPEG_0 0
#define SCE_LPEG_1 1
#define SCE_LPEG_2 2
#define SCE_LPEG_3 3
#define SCE_LPEG_4 4
#define SCE_LPEG_5 5
#define SCE_LPEG_6 6
#define SCE_LPEG_7 7
#define SCE_LPEG_8 8
#define SCE_LPEG_9 9
#define SCE_LPEG_10 10
#define SCE_LPEG_11 11
#define SCE_LPEG_12 12
#define SCE_LPEG_13 13
#define SCE_LPEG_14 14
#define SCE_LPEG_15 15
#define SCE_LPEG_16 16
#define SCE_LPEG_17 17
#define SCE_LPEG_18 18
#define SCE_LPEG_19 19
#define SCE_LPEG_20 20
#define SCE_LPEG_21 21
#define SCE_LPEG_22 22
#define SCE_LPEG_23 23
#define SCE_LPEG_24 24
#define SCE_LPEG_25 25
#define SCE_LPEG_26 26
#define SCE_LPEG_27 27
#define SCE_LPEG_28 28
#define SCE_LPEG_29 29
#define SCE_LPEG_30 30
#define SCE_LPEG_31 31
#define SCE_LPEG_32 32
#define SCE_LPEG_33 33
#define SCE_LPEG_34 34
#define SCE_LPEG_35 35
#define SCE_LPEG_36 36
#define SCE_LPEG_37 37
#define SCE_LPEG_38 38
#define SCE_LPEG_39 39
#define SCE_LPEG_40 40
#define SCE_LPEG_41 41
#define SCE_LPEG_42 42
#define SCE_LPEG_43 43
#define SCE_LPEG_44 44
#define SCE_LPEG_45 45
#define SCE_LPEG_46 46
#define SCE_LPEG_47 47
#define SCE_LPEG_48 48
#define SCE_LPEG_49 49
#define SCE_LPEG_50 50
#define SCE_LPEG_51 51
#define SCE_LPEG_52 52
#define SCE_LPEG_53 53
#define SCE_LPEG_54 54
#define SCE_LPEG_55 55
#define SCE_LPEG_56 56
#define SCE_LPEG_57 57
#define SCE_LPEG_58 58
#define SCE_LPEG_59 59
#define SCE_LPEG_60 60
#define SCE_LPEG_61 61
#define SCE_LPEG_62 62
#define SCE_LPEG_63 63
#define SCE_LPEG_64 64
#define SCE_LPEG_65 65
#define SCE_LPEG_66 66
#define SCE_LPEG_67 67
#define SCE_LPEG_68 68
#define SCE_LPEG_69 69
#define SCE_LPEG_70 70
#define SCE_LPEG_71 71
#define SCE_LPEG_72 72
#define SCE_LPEG_73 73
#define SCE_LPEG_74 74
#define SCE_LPEG_75 75
#define SCE_LPEG_76 76
#define SCE_LPEG_77 77
#define SCE_LPEG_78 78
#define SCE_LPEG_79 79
#define SCE_LPEG_80 80
#define SCE_LPEG_81 81
#define SCE_LPEG_82 82
#define SCE_LPEG_83 83
#define SCE_LPEG_84 84
#define SCE_LPEG_85 85
#define SCE_LPEG_86 86
#define SCE_LPEG_87 87
#define SCE_LPEG_88 88
#define SCE_LPEG_89 89
#define SCE_LPEG_90 90
#define SCE_LPEG_91 91
#define SCE_LPEG_92 92
#define SCE_LPEG_93 93
#define SCE_LPEG_94 94
#define SCE_LPEG_95 95
#define SCE_LPEG_96 96
#define SCE_LPEG_97 97
#define SCE_LPEG_98 98
#define SCE_LPEG_99 99
#define SCE_LPEG_100 100
#define SCE_LPEG_101 101
#define SCE_LPEG_102 102
#define SCE_LPEG_103 103
#define SCE_LPEG_104 104
#define SCE_LPEG_105 105
#define SCE_LPEG_106 106
#define SCE_LPEG_107 107
#define SCE_LPEG_108 108
#define SCE_LPEG_109 109
#define SCE_LPEG_110 110
#define SCE_LPEG_111 111
#define SCE_LPEG_112 112
#define SCE_LPEG_113 113
#define SCE_LPEG_114 114
#define SCE_LPEG_115 115
#define SCE_LPEG_116 116
#define SCE_LPEG_117 117
#define SCE_LPEG_118 118
#define SCE_LPEG_119 119
#define SCE_LPEG_120 120
#define SCE_LPEG_121 121
#define SCE_LPEG_122 122
#define SCE_LPEG_123 123
#define SCE_LPEG_124 124
#define SCE_LPEG_125 125
#define SCE_LPEG_126 126
#define SCE_LPEG_127 127
//--Autogenerated -- end of section automatically generated from Scintilla.iface
// end modified by Mitchell

#endif
